apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shoppingstore-ingress
  namespace: default
  annotations:
    # Tells your new controller to provision a standard AWS Application Load Balancer
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          # Routes all standard web traffic straight to your React frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ecommerce-frontend-service
                port:
                  number: 80